
/*
 Copyright 2013 Vinicius Vasco Pedron, Luiz Gustavo Royer, Gelson Lemes,
    JoÃ£o Ricardo Oliveira, HÃ©lio Campos, Maycon Willian Nunes Prestes
*/

/*
   Este arquivo Ã© parte do programa OpenBeta

    OpenBeta Ã© um software livre; vocÃª pode redistribuÃ­-lo e/ou 
    modificÃ¡-lo dentro dos termos da LicenÃ§a PÃºblica Geral GNU como 
    publicada pela FundaÃ§Ã£o do Software Livre (FSF); na versÃ£o 2 da 
    LicenÃ§a, ou (na sua opiniÃ£o) qualquer versÃ£o.

    Este programa Ã© distribuÃ­do na esperanÃ§a de que possa ser  Ãºtil, 
    mas SEM NENHUMA GARANTIA; sem uma garantia implÃ­cita de ADEQUAÃ‡ÃƒO a qualquer
    MERCADO ou APLICAÃ‡ÃƒO EM PARTICULAR. Veja a
    LicenÃ§a PÃºblica Geral GNU para maiores detalhes.

    VocÃª deve ter recebido uma cÃ³pia da LicenÃ§a PÃºblica Geral GNU
    junto com este programa, se nÃ£o, escreva para a FundaÃ§Ã£o do Software
    Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

package br.com.openbeta.visao;

import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author gelson
 */
public class TAlteracao_Exclusao extends javax.swing.JFrame {

    /**
     * Creates new form TCadastro
     */
    public TAlteracao_Exclusao() {
        initComponents();
        jTNome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jBFechar = new javax.swing.JButton();
        jBFechar1 = new javax.swing.JButton();
        jBFechar2 = new javax.swing.JButton();
        jTabprof1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jTCodigo = new javax.swing.JTextField();
        jTRG = new javax.swing.JTextField();
        jTNome = new javax.swing.JTextField();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox();
        jLabel144 = new javax.swing.JLabel();
        jTCelular2 = new javax.swing.JTextField();
        jLabel148 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jTCPF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel149 = new javax.swing.JLabel();
        jTCidadeNatal = new javax.swing.JTextField();
        jLabel150 = new javax.swing.JLabel();
        jComboBoxUFNatal = new javax.swing.JComboBox();
        jLabel151 = new javax.swing.JLabel();
        jTDataNascimento = new javax.swing.JTextField();
        jLabel152 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel153 = new javax.swing.JLabel();
        jTEnderecoRua = new javax.swing.JTextField();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jTEnderecoLogradouro = new javax.swing.JTextField();
        jTEnderecoNumero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jTEnderecoBairro = new javax.swing.JTextField();
        jLabel136 = new javax.swing.JLabel();
        jTEnderecoCidade = new javax.swing.JTextField();
        jLabel143 = new javax.swing.JLabel();
        jTEnderecoCEP = new javax.swing.JTextField();
        jComboBoxUFEndereco = new javax.swing.JComboBox();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabel157 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jTTelefoneResidencial = new javax.swing.JTextField();
        jLabel147 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jTEmail1 = new javax.swing.JTextField();
        jLabel158 = new javax.swing.JLabel();
        jTEmail2 = new javax.swing.JTextField();
        jTCelular1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTExtras = new javax.swing.JTextPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel159 = new javax.swing.JLabel();
        jComboBoxAnoConclusao = new javax.swing.JComboBox();
        jLabel160 = new javax.swing.JLabel();
        jTNomeInstituicao = new javax.swing.JTextField();
        jLabel161 = new javax.swing.JLabel();
        jComboBoxGraduacao = new javax.swing.JComboBox();
        jBAdicionarGraduacao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGraduacoes = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel162 = new javax.swing.JLabel();
        jComboBoxGraduacao1 = new javax.swing.JComboBox();
        jBAdicionarGraduacao1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableGraduacoes1 = new javax.swing.JTable();
        jLabel165 = new javax.swing.JLabel();
        jComboBoxGraduacao2 = new javax.swing.JComboBox();
        jLabel166 = new javax.swing.JLabel();
        jComboBoxGraduacao3 = new javax.swing.JComboBox();
        jLabel167 = new javax.swing.JLabel();
        jComboBoxGraduacao4 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(155, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(845, 705));
        setResizable(false);

        jPanel10.setBackground(new java.awt.Color(0, 102, 0));
        jPanel10.setForeground(new java.awt.Color(0, 0, 102));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 800));

        jBFechar.setBackground(new java.awt.Color(204, 204, 204));
        jBFechar.setText("Alterar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });
        jBFechar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBFecharFocusGained(evt);
            }
        });
        jBFechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBFecharKeyPressed(evt);
            }
        });

        jBFechar1.setBackground(new java.awt.Color(204, 204, 204));
        jBFechar1.setText("Excluir");
        jBFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFechar1ActionPerformed(evt);
            }
        });
        jBFechar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBFechar1FocusGained(evt);
            }
        });
        jBFechar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBFechar1KeyPressed(evt);
            }
        });

        jBFechar2.setBackground(new java.awt.Color(204, 204, 204));
        jBFechar2.setText("Fechar");
        jBFechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFechar2ActionPerformed(evt);
            }
        });
        jBFechar2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBFechar2FocusGained(evt);
            }
        });
        jBFechar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBFechar2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jBFechar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jBFechar2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBFechar2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabprof1.setForeground(new java.awt.Color(0, 0, 51));
        jTabprof1.setMaximumSize(new java.awt.Dimension(800, 800));
        jTabprof1.setMinimumSize(new java.awt.Dimension(800, 800));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setAlignmentX(150.0F);
        jPanel6.setFocusCycleRoot(true);
        jPanel6.setMaximumSize(new java.awt.Dimension(847, 847));
        jPanel6.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigojTextField11ActionPerformed(evt);
            }
        });
        jPanel6.add(jTCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, -1));

        jTRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRGActionPerformed(evt);
            }
        });
        jPanel6.add(jTRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 100, -1));

        jTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeActionPerformed(evt);
            }
        });
        jPanel6.add(jTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 630, -1));

        jLabel137.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel137.setText("* CÃ³digo:");
        jPanel6.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 20));

        jLabel138.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel138.setText("* RG:");
        jPanel6.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 30, 20));

        jLabel141.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel141.setText("* CPF:");
        jLabel141.setToolTipText("");
        jPanel6.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel142.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel142.setText("* SituaÃ§Ã£o:");
        jPanel6.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 70, 20));

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "EM ATIVIDADE", "AFASTADO DA FUNÃ‡ÃƒO", "LICENÃ‡A MÃ‰DICA", "LICENÃ‡A PRÃŠMIO", "READAPTADOS" }));
        jComboBoxSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacaoActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBoxSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 170, -1));

        jLabel144.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel144.setText("* Celular ObrigatÃ³rio:");
        jPanel6.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 110, 20));
        jPanel6.add(jTCelular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 220, -1));

        jLabel148.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel148.setText(" Extras:");
        jPanel6.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 50, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("* Estado Civil:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 80, 20));

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "SOLTEIRO", "CASADO", "DIVORCIADO", "VIÃšVO" }));
        jComboBoxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoCivilActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBoxEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 100, -1));
        jPanel6.add(jTCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("*   Campos de preenchimento obrigatÃ³rio");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, -1, 20));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "  Natual de  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jLabel149.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel149.setText("* Cidade:");

        jTCidadeNatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCidadeNataljTextField4ActionPerformed(evt);
            }
        });

        jLabel150.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel150.setText(" * UF:");
        jLabel150.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxUFNatal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "PR" }));
        jComboBoxUFNatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUFNataljComboBox3ActionPerformed(evt);
            }
        });

        jLabel151.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel151.setText("* Data de Nascimento:");

        jTDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDataNascimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel149, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTCidadeNatal, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel150)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxUFNatal, 0, 69, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jLabel151)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCidadeNatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel150)
                    .addComponent(jComboBoxUFNatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel151, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel149)
                    .addComponent(jTDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 680, 60));

        jLabel152.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel152.setText("* Nome:");
        jPanel6.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 20));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "  EndereÃ§o  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jLabel153.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel153.setText("* EndereÃ§o:");

        jTEnderecoRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEnderecoRuajTextField4ActionPerformed(evt);
            }
        });

        jLabel154.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel154.setText("* UF:");
        jLabel154.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel155.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel155.setText("* Logradouro:");

        jTEnderecoLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEnderecoLogradouroActionPerformed(evt);
            }
        });

        jTEnderecoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEnderecoNumeroActionPerformed(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("* NÂº:");

        jLabel139.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel139.setText("* Bairro:");

        jLabel136.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel136.setText("* Cidade:");

        jLabel143.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel143.setText("* CEP:");

        jComboBoxUFEndereco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "PR" }));
        jComboBoxUFEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUFEnderecojComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel155)
                    .addComponent(jLabel136)
                    .addComponent(jLabel139))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTEnderecoCidade)
                        .addComponent(jTEnderecoBairro)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(jTEnderecoRua, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jTEnderecoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel153)))
                .addGap(9, 9, 9)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTEnderecoNumero))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel143)
                            .addComponent(jLabel154))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTEnderecoCEP)
                            .addComponent(jComboBoxUFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEnderecoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel153)
                    .addComponent(jTEnderecoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel155, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEnderecoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel136, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEnderecoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel154)
                    .addComponent(jComboBoxUFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel139, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEnderecoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel143, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEnderecoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 680, 120));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "MASCULINO", "FEMININO" }));
        jPanel6.add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 100, -1));

        jLabel157.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel157.setText("* Sexo:");
        jPanel6.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 80, 40, 20));

        jLabel146.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel146.setText(" Telefone Residencial:");
        jPanel6.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 120, 20));
        jPanel6.add(jTTelefoneResidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 220, 20));

        jLabel147.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel147.setText(" Celular Opcional:");
        jPanel6.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 90, 20));

        jLabel156.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel156.setText("* E-Mail ObrigatÃ³rio:");
        jPanel6.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 110, 20));
        jPanel6.add(jTEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 560, -1));

        jLabel158.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel158.setText(" E-Mail Opcional:");
        jPanel6.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 110, 20));
        jPanel6.add(jTEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 560, -1));
        jPanel6.add(jTCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 220, -1));

        jScrollPane1.setViewportView(jTExtras);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 560, 90));

        jTabprof1.addTab("Dados Pessoais", jPanel6);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel159.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel159.setText("* GraduaÃ§Ã£o:");
        jPanel8.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 20));

        jComboBoxAnoConclusao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        jComboBoxAnoConclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnoConclusaoActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxAnoConclusao, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 70, -1));

        jLabel160.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel160.setText("* InstituiÃ§Ã£o:");
        jPanel8.add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 20));

        jTNomeInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeInstituicaoActionPerformed(evt);
            }
        });
        jPanel8.add(jTNomeInstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 610, -1));

        jLabel161.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel161.setText("* Ano de ConclusÃ£o:");
        jPanel8.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 110, 20));

        jComboBoxGraduacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "BACHARELADO", "LICENCIATURA", "TECNÃ“LOGO", "ESPECIALIZAÃ‡ÃƒO", "PÃ“S-GRADUAÃ‡ÃƒO", "MESTRADO", "DOUTORADO" }));
        jComboBoxGraduacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGraduacaoActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxGraduacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, -1));

        jBAdicionarGraduacao.setBackground(new java.awt.Color(204, 204, 204));
        jBAdicionarGraduacao.setText("Adicionar");
        jBAdicionarGraduacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarGraduacaoActionPerformed(evt);
            }
        });
        jBAdicionarGraduacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBAdicionarGraduacaoFocusGained(evt);
            }
        });
        jBAdicionarGraduacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBAdicionarGraduacaoKeyPressed(evt);
            }
        });
        jPanel8.add(jBAdicionarGraduacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, 30));

        jTableGraduacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableGraduacoes.setRowHeight(25);
        jTableGraduacoes.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jTableGraduacoes);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 680, 480));

        jTabprof1.addTab("GraduaÃ§Ãµes", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel162.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel162.setText("* FunÃ§Ã£o:");
        jPanel9.add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));

        jComboBoxGraduacao1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "ESPANHOL", "INGLES", "ITALIANO", "FRANCÃŠS", "BANCO DE DADOS", "REDES E S.O.", "INFORMÃ�TICA INSTRUMENTAL" }));
        jComboBoxGraduacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGraduacao1ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBoxGraduacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 280, -1));

        jBAdicionarGraduacao1.setBackground(new java.awt.Color(204, 204, 204));
        jBAdicionarGraduacao1.setText("Adicionar");
        jBAdicionarGraduacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarGraduacao1ActionPerformed(evt);
            }
        });
        jBAdicionarGraduacao1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBAdicionarGraduacao1FocusGained(evt);
            }
        });
        jBAdicionarGraduacao1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBAdicionarGraduacao1KeyPressed(evt);
            }
        });
        jPanel9.add(jBAdicionarGraduacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, 30));

        jTableGraduacoes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableGraduacoes1.setRowHeight(25);
        jTableGraduacoes1.setRowSelectionAllowed(false);
        jScrollPane3.setViewportView(jTableGraduacoes1);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 680, 480));

        jLabel165.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel165.setText("* Sub-setor ou Disciplina:");
        jPanel9.add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 140, 20));

        jComboBoxGraduacao2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "PROFESSOR", "FUNCIONÃ�RIO", "PEDAGOGIA" }));
        jComboBoxGraduacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGraduacao2ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBoxGraduacao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 150, -1));

        jLabel166.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel166.setText("* Setor ou Curso: ");
        jPanel9.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 100, 20));

        jComboBoxGraduacao3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "ENSINO FUNDAMENTAL", "ENSINO MÃ‰DIO", "CELEM", "TÃ‰CNICO INFORMÃ�TICA - SUBSEQUENTE", "TÃ‰CNICO INFORMÃ�TICA - INTEGRAL" }));
        jComboBoxGraduacao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGraduacao3ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBoxGraduacao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 280, 20));

        jLabel167.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel167.setText("* Turno:");
        jPanel9.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 20));

        jComboBoxGraduacao4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "MATUTINO", "VERPERTINO", "NOTURNO" }));
        jComboBoxGraduacao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGraduacao4ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBoxGraduacao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, -1));

        jTabprof1.addTab("FunÃ§Ãµes", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabprof1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, Short.MAX_VALUE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabprof1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCodigojTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigojTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCodigojTextField11ActionPerformed

    private void jTRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRGActionPerformed

    private void jTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeActionPerformed

    private void jComboBoxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoCivilActionPerformed

    private void jTEnderecoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEnderecoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnderecoNumeroActionPerformed

    private void jTCidadeNataljTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCidadeNataljTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCidadeNataljTextField4ActionPerformed

    private void jComboBoxUFNataljComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUFNataljComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUFNataljComboBox3ActionPerformed

    private void jTDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDataNascimentoActionPerformed

    private void jTEnderecoRuajTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEnderecoRuajTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnderecoRuajTextField4ActionPerformed

    private void jTEnderecoLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEnderecoLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnderecoLogradouroActionPerformed

    private void jComboBoxUFEnderecojComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUFEnderecojComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUFEnderecojComboBox3ActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed

    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBFecharFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBFecharFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFecharFocusGained

    private void jBFecharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBFecharKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFecharKeyPressed

    private void jComboBoxAnoConclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnoConclusaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAnoConclusaoActionPerformed

    private void jTNomeInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeInstituicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeInstituicaoActionPerformed

    private void jComboBoxGraduacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGraduacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGraduacaoActionPerformed

    private void jBAdicionarGraduacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarGraduacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAdicionarGraduacaoActionPerformed

    private void jBAdicionarGraduacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBAdicionarGraduacaoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAdicionarGraduacaoFocusGained

    private void jBAdicionarGraduacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBAdicionarGraduacaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAdicionarGraduacaoKeyPressed

    private void jComboBoxGraduacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGraduacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGraduacao1ActionPerformed

    private void jBAdicionarGraduacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarGraduacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAdicionarGraduacao1ActionPerformed

    private void jBAdicionarGraduacao1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBAdicionarGraduacao1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAdicionarGraduacao1FocusGained

    private void jBAdicionarGraduacao1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBAdicionarGraduacao1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAdicionarGraduacao1KeyPressed

    private void jComboBoxGraduacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGraduacao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGraduacao2ActionPerformed

    private void jComboBoxGraduacao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGraduacao3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGraduacao3ActionPerformed

    private void jComboBoxGraduacao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGraduacao4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGraduacao4ActionPerformed

    private void jComboBoxSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSituacaoActionPerformed

    private void jBFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFechar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFechar1ActionPerformed

    private void jBFechar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBFechar1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFechar1FocusGained

    private void jBFechar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBFechar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFechar1KeyPressed

    private void jBFechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFechar2ActionPerformed
        this.dispose();       
    }//GEN-LAST:event_jBFechar2ActionPerformed

    private void jBFechar2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBFechar2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFechar2FocusGained

    private void jBFechar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBFechar2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFechar2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {

        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    javax.swing.UIManager.setLookAndFeel(new MetalLookAndFeel());
                    break;
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TAlteracao_Exclusao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionarGraduacao;
    private javax.swing.JButton jBAdicionarGraduacao1;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBFechar1;
    private javax.swing.JButton jBFechar2;
    private javax.swing.JComboBox jComboBoxAnoConclusao;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JComboBox jComboBoxGraduacao;
    private javax.swing.JComboBox jComboBoxGraduacao1;
    private javax.swing.JComboBox jComboBoxGraduacao2;
    private javax.swing.JComboBox jComboBoxGraduacao3;
    private javax.swing.JComboBox jComboBoxGraduacao4;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxSituacao;
    private javax.swing.JComboBox jComboBoxUFEndereco;
    private javax.swing.JComboBox jComboBoxUFNatal;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTCPF;
    private javax.swing.JTextField jTCelular1;
    private javax.swing.JTextField jTCelular2;
    private javax.swing.JTextField jTCidadeNatal;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTDataNascimento;
    private javax.swing.JTextField jTEmail1;
    private javax.swing.JTextField jTEmail2;
    private javax.swing.JTextField jTEnderecoBairro;
    private javax.swing.JTextField jTEnderecoCEP;
    private javax.swing.JTextField jTEnderecoCidade;
    private javax.swing.JTextField jTEnderecoLogradouro;
    private javax.swing.JTextField jTEnderecoNumero;
    private javax.swing.JTextField jTEnderecoRua;
    private javax.swing.JTextPane jTExtras;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNomeInstituicao;
    private javax.swing.JTextField jTRG;
    private javax.swing.JTextField jTTelefoneResidencial;
    private javax.swing.JTable jTableGraduacoes;
    private javax.swing.JTable jTableGraduacoes1;
    private javax.swing.JTabbedPane jTabprof1;
    // End of variables declaration//GEN-END:variables
}
