/*
 Copyright 2013 Vinicius Vasco Pedron, Luiz Gustavo Royer, Gelson Lemes,
    JoÃ£o Ricardo Oliveira, HÃ©lio Campos, Maycon Willian Nunes Prestes
*/

/*
   Este arquivo Ã© parte do programa OpenBeta

    OpenBeta Ã© um software livre; vocÃª pode redistribuÃ­-lo e/ou 
    modificÃ¡-lo dentro dos termos da LicenÃ§a PÃºblica Geral GNU como 
    publicada pela FundaÃ§Ã£o do Software Livre (FSF); na versÃ£o 2 da 
    LicenÃ§a, ou (na sua opiniÃ£o) qualquer versÃ£o.

    Este programa Ã© distribuÃ­do na esperanÃ§a de que possa ser  Ãºtil, 
    mas SEM NENHUMA GARANTIA; sem uma garantia implÃ­cita de ADEQUAÃ‡ÃƒO a qualquer
    MERCADO ou APLICAÃ‡ÃƒO EM PARTICULAR. Veja a
    LicenÃ§a PÃºblica Geral GNU para maiores detalhes.

    VocÃª deve ter recebido uma cÃ³pia da LicenÃ§a PÃºblica Geral GNU
    junto com este programa, se nÃ£o, escreva para a FundaÃ§Ã£o do Software
    Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

package br.com.openbeta.visao;

import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

import br.com.openbeta.utilitarios.Md5;
import br.com.openbeta.utilitarios.ValidaCPF;
public class TAlteracaoSenha extends javax.swing.JFrame {

    
    public TAlteracaoSenha() {
        initComponents();
         
//        jTCPF.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLSenhaAnterior = new javax.swing.JLabel();
        jTCPF = new javax.swing.JTextField();
        jBOK = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jBcancelar = new javax.swing.JButton();
        jLSenhaAtual = new javax.swing.JLabel();
        jLSenhaAtual2 = new javax.swing.JLabel();
        jLSenhaAtual3 = new javax.swing.JLabel();
        jTSenhaAnterior = new javax.swing.JPasswordField();
        jTSenhaNova = new javax.swing.JPasswordField();
        jTSenhaNovaConfirmacao = new javax.swing.JPasswordField();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(400, 250, 410, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(410, 240));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("framecadastro"); // NOI18N
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("Segoe Script", 3, 48)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("OpenBeta");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 11, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tunga", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("VersÃ£o 1.0");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 100));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 430, -1));

        jLSenhaAnterior.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLSenhaAnterior.setForeground(new java.awt.Color(0, 0, 51));
        jLSenhaAnterior.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLSenhaAnterior.setText("Digite seu CPF - somente nÃºmeros:");
        jLSenhaAnterior.setToolTipText("");
        jLSenhaAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLSenhaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, -1));

        jTCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTCPF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTCPF.setToolTipText("Digite um CPF vÃ¡lido");
        jTCPF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTCPF.setFocusCycleRoot(true);
        jTCPF.setFocusTraversalPolicy(null);
        jTCPF.setFocusTraversalPolicyProvider(true);
        jTCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCPFActionPerformed(evt);
            }
        });
        jTCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTCPFFocusLost(evt);
            }
        });
        jTCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCPFKeyPressed(evt);
            }
        });
        getContentPane().add(jTCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 140, -1));

        jBOK.setBackground(new java.awt.Color(204, 204, 204));
        jBOK.setText("ALTERAR");
        jBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOKActionPerformed(evt);
            }
        });
        jBOK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBOKFocusGained(evt);
            }
        });
        jBOK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBOKKeyPressed(evt);
            }
        });
        getContentPane().add(jBOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 430, 10));

        jBcancelar.setBackground(new java.awt.Color(204, 204, 204));
        jBcancelar.setText("CANCELAR");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 140, 30));

        jLSenhaAtual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLSenhaAtual.setForeground(new java.awt.Color(0, 0, 51));
        jLSenhaAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLSenhaAtual.setText("Digite sua senha anterior:");
        jLSenhaAtual.setToolTipText("");
        jLSenhaAtual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, -1));

        jLSenhaAtual2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLSenhaAtual2.setForeground(new java.awt.Color(0, 0, 51));
        jLSenhaAtual2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLSenhaAtual2.setText("Digite sua nova senha:");
        jLSenhaAtual2.setToolTipText("");
        jLSenhaAtual2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLSenhaAtual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        jLSenhaAtual3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLSenhaAtual3.setForeground(new java.awt.Color(0, 0, 51));
        jLSenhaAtual3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLSenhaAtual3.setText("Digite novamente sua nova senha:");
        jLSenhaAtual3.setToolTipText("");
        jLSenhaAtual3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLSenhaAtual3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 220, -1));

        jTSenhaAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTSenhaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSenhaAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jTSenhaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 140, -1));

        jTSenhaNova.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTSenhaNova, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 140, -1));

        jTSenhaNovaConfirmacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTSenhaNovaConfirmacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCPFActionPerformed

    }//GEN-LAST:event_jTCPFActionPerformed

    private void jBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOKActionPerformed
        String cpf = jTCPF.getText();
        String senha_anterior = jTSenhaAnterior.getText();
        String senha_nova = jTSenhaNova.getText();
        String senha_nova_confirmacao = jTSenhaNovaConfirmacao.getText();    
        
        System.out.println(Md5.usuario_principal);
        System.out.println(Md5.senha_principal);
        
        boolean cpfCorreto = ValidaCPF.isCPF(cpf);
        
        if (cpfCorreto) {
            if (!(cpf.equals(Md5.usuario_principal))) {
                JOptionPane.showMessageDialog(null,"CPF nÃ£o confere!","CPF INCORRETO",JOptionPane.ERROR_MESSAGE);
            } else if (!(senha_anterior.equals(Md5.senha_principal))) {
                JOptionPane.showMessageDialog(null,"Senha anterior nÃ£o confere!","SENHA INCORRETA",JOptionPane.ERROR_MESSAGE);
            } else if (!(senha_nova_confirmacao.equals(senha_nova))) {
                JOptionPane.showMessageDialog(null,"Senhas nÃ£o conferem!","SENHA INCORRETA",JOptionPane.ERROR_MESSAGE);
            } else if ((senha_nova_confirmacao.equals(senha_anterior)) || (senha_nova.equals(senha_anterior))) {
                JOptionPane.showMessageDialog(null,"Nova senha precisa ser diferente da senha anterior!","NOVA SENHA INVÃ�LIDA",JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null,"Senha alterada com sucesso!","SENHA ALTERADA",JOptionPane.INFORMATION_MESSAGE);
                new TelaMenu().setVisible(true);
                TAlteracaoSenha.this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF InvÃ¡lido!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBOKActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        if ("CARMELO123".equals(Md5.senha_principal)) {
            new TelaInicial().setVisible(true);
            TAlteracaoSenha.this.dispose();
        } else {
            new TelaMenu().setVisible(true);
            TAlteracaoSenha.this.dispose();
        }
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jTCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTCPFFocusGained
   
    }//GEN-LAST:event_jTCPFFocusGained

    private void jBOKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBOKFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBOKFocusGained

    private void jTCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCPFKeyPressed
        // TODO add your handling code here:
//        String n;
//        n = String.valueOf(jTCPF.getText());
//
//        if (evt.getKeyCode() == 10) {
//            if (n.equals("")) {
//                JOptionPane.showMessageDialog(null, "Entre com cÃ³digo do usuÃ¡rio", "ERRO", JOptionPane.ERROR_MESSAGE);
//            } else {
//                jTsenha.requestFocus();
//            }
//        }
    }//GEN-LAST:event_jTCPFKeyPressed

    private void jBOKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBOKKeyPressed
        // TODO add your handling code here:
//        if (evt.getKeyCode() == 10) {
//            usuario = jTCPF.getText();
//            senha = jTsenha.getText().toString();
//            Md5.md5(usuario, senha);
//            TAlteracaoSenha.this.dispose();
//        }
    }//GEN-LAST:event_jBOKKeyPressed

    private void jTCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTCPFFocusLost

    }//GEN-LAST:event_jTCPFFocusLost

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void jTSenhaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSenhaAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSenhaAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {

        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    javax.swing.UIManager.setLookAndFeel(new MetalLookAndFeel());
                    break;
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOK;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLSenhaAnterior;
    private javax.swing.JLabel jLSenhaAtual;
    private javax.swing.JLabel jLSenhaAtual2;
    private javax.swing.JLabel jLSenhaAtual3;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTCPF;
    private javax.swing.JPasswordField jTSenhaAnterior;
    private javax.swing.JPasswordField jTSenhaNova;
    private javax.swing.JPasswordField jTSenhaNovaConfirmacao;
    // End of variables declaration//GEN-END:variables

    
}

