/*
 Copyright 2013 Vinicius Vasco Pedron, Luiz Gustavo Royer, Gelson Lemes,
    JoÃ£o Ricardo Oliveira, HÃ©lio Campos, Maycon Willian Nunes Prestes
*/

/*
   Este arquivo Ã© parte do programa OpenBeta

    OpenBeta Ã© um software livre; vocÃª pode redistribuÃ­-lo e/ou 
    modificÃ¡-lo dentro dos termos da LicenÃ§a PÃºblica Geral GNU como 
    publicada pela FundaÃ§Ã£o do Software Livre (FSF); na versÃ£o 2 da 
    LicenÃ§a, ou (na sua opiniÃ£o) qualquer versÃ£o.

    Este programa Ã© distribuÃ­do na esperanÃ§a de que possa ser  Ãºtil, 
    mas SEM NENHUMA GARANTIA; sem uma garantia implÃ­cita de ADEQUAÃ‡ÃƒO a qualquer
    MERCADO ou APLICAÃ‡ÃƒO EM PARTICULAR. Veja a
    LicenÃ§a PÃºblica Geral GNU para maiores detalhes.

    VocÃª deve ter recebido uma cÃ³pia da LicenÃ§a PÃºblica Geral GNU
    junto com este programa, se nÃ£o, escreva para a FundaÃ§Ã£o do Software
    Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

package br.com.openbeta.visao;

import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

import br.com.openbeta.controle.EAO;
import br.com.openbeta.modelo.Atividade;
import br.com.openbeta.modelo.Cargo;
import br.com.openbeta.modelo.Contratacao;
import br.com.openbeta.modelo.Endereco;
import br.com.openbeta.modelo.Estado;
import br.com.openbeta.modelo.EstadoCivil;
import br.com.openbeta.modelo.Funcao;
import br.com.openbeta.modelo.FuncaoPessoa;
import br.com.openbeta.modelo.Graduacao;
import br.com.openbeta.modelo.GraduacaoPessoa;
import br.com.openbeta.modelo.Pessoa;
import br.com.openbeta.modelo.Setor;
import br.com.openbeta.modelo.Sexo;
import br.com.openbeta.modelo.Situacao;
import br.com.openbeta.modelo.SubSetor;
import br.com.openbeta.modelo.TelefoneResidencial;
import br.com.openbeta.modelo.TelefoneResidencialPessoa;
import br.com.openbeta.modelo.TipoGraduacao;
import br.com.openbeta.modelo.Turno;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author gelson
 */
public class TConsulta extends javax.swing.JFrame {
    
    private EAO eao = new EAO(Pessoa.class);
    private EAO eao2 = new EAO(Graduacao.class);
    private Pessoa pessoa = new Pessoa();
    private Situacao situacao = new Situacao();
    private EstadoCivil estado_civil = new EstadoCivil();
    private Sexo sexo = new Sexo();
    private Estado estado = new Estado();
    private Endereco endereco = new Endereco();
    private TelefoneResidencial telefone_residencial = new TelefoneResidencial();
    private Atividade atividade = new Atividade();
    private Contratacao contratacao = new Contratacao();
    private Graduacao graduacao = new Graduacao();
    private TipoGraduacao tipo_graduacao = new TipoGraduacao(); 
    private Funcao funcao = new Funcao();
    private Cargo cargo = new Cargo();
    private Setor setor = new Setor();
    private SubSetor sub_setor = new SubSetor();
    private Turno turno = new Turno();
    private TelefoneResidencialPessoa telefone_residencial_pessoa = new TelefoneResidencialPessoa();
    private GraduacaoPessoa graduacao_pessoa = new GraduacaoPessoa();
    private FuncaoPessoa funcao_pessoa = new FuncaoPessoa();

    /**
     * Creates new form TCadastro
     */
    public TConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jBGravar = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jTabprof1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTCodigo1 = new javax.swing.JTextField();
        jTNome1 = new javax.swing.JTextField();
        jComboBoxGraduacao4 = new javax.swing.JComboBox();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBoxGraduacao1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(155, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jPanel10.setBackground(new java.awt.Color(102, 0, 0));
        jPanel10.setForeground(new java.awt.Color(0, 0, 102));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 800));

        jBGravar.setBackground(new java.awt.Color(204, 204, 204));
        jBGravar.setText("Pesquisar");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });
        jBGravar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBGravarFocusGained(evt);
            }
        });
        jBGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBGravarKeyPressed(evt);
            }
        });

        jBLimpar.setBackground(new java.awt.Color(204, 204, 204));
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });
        jBLimpar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBLimparFocusGained(evt);
            }
        });
        jBLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBLimparKeyPressed(evt);
            }
        });

        jBFechar.setBackground(new java.awt.Color(204, 204, 204));
        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });
        jBFechar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBFecharFocusGained(evt);
            }
        });
        jBFechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBFecharKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jBLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabprof1.setForeground(new java.awt.Color(0, 0, 51));
        jTabprof1.setMaximumSize(new java.awt.Dimension(800, 800));
        jTabprof1.setMinimumSize(new java.awt.Dimension(800, 800));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setAlignmentX(150.0F);
        jPanel6.setFocusCycleRoot(true);
        jPanel6.setMaximumSize(new java.awt.Dimension(847, 847));
        jPanel6.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setText("Nome");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, -1));

        jRadioButton2.setText("Sub-setor ou Disciplina:");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 150, -1));

        jRadioButton3.setText("CÃ³digo");
        jRadioButton3.setHideActionText(true);
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        jTCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigo1jTextField11ActionPerformed(evt);
            }
        });
        jPanel6.add(jTCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jTNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNome1ActionPerformed(evt);
            }
        });
        jPanel6.add(jTNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 530, -1));

        jComboBoxGraduacao4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "ENSINO FUNDAMENTAL", "ENSINO MÃ‰DIO", "CELEM", "TÃ‰CNICO INFORMÃ�TICA - SUBSEQUENTE", "TÃ‰CNICO INFORMÃ�TICA - INTEGRAL" }));
        jComboBoxGraduacao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGraduacao4ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBoxGraduacao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, 20));

        jRadioButton4.setText("Setor ou curso");
        jRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        jComboBoxGraduacao1.setModel(new DefaultComboBoxModel(new String[] {"Selecione", "ESPANHOL", "INGLES", "ITALIANO", "FRANCES", "BANCO DE DADOS", "REDES E S.O.", "INFORMATICA INSTRUMENTAL"}));
        jComboBoxGraduacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGraduacao1ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBoxGraduacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 310, 20));

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableConsulta);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 680, 440));

        jTabprof1.addTab("Consulta", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabprof1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, Short.MAX_VALUE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabprof1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBGravarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBGravarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBGravarFocusGained

    private void jBGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBGravarKeyPressed
        if (jRadioButton3.isSelected()) {
            String codigo = jTCodigo1.getText().toString();
            eao.consulta(codigo);
            jTNome1.setText(pessoa.getnome().toString());
        }       
    }//GEN-LAST:event_jBGravarKeyPressed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        TConsulta.this.dispose();
        new TConsulta().setVisible(true);
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jBLimparFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBLimparFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLimparFocusGained

    private void jBLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBLimparKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLimparKeyPressed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBFecharFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBFecharFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFecharFocusGained

    private void jBFecharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBFecharKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFecharKeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTCodigo1jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigo1jTextField11ActionPerformed
///
    }//GEN-LAST:event_jTCodigo1jTextField11ActionPerformed

    private void jTNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNome1ActionPerformed

    private void jComboBoxGraduacao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGraduacao4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGraduacao4ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jComboBoxGraduacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGraduacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGraduacao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {

        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    javax.swing.UIManager.setLookAndFeel(new MetalLookAndFeel());
                    break;
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TConsulta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBGravar;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JComboBox jComboBoxGraduacao1;
    private javax.swing.JComboBox jComboBoxGraduacao4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigo1;
    private javax.swing.JTextField jTNome1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTabbedPane jTabprof1;
    // End of variables declaration//GEN-END:variables
}
